# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: mvn -B clean verify --file Calidad-Maven/pom.xml

    - name: Reporte de covertura de jacoco
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: Calidad-Maven/target/site/jacoco/

    - name: Generamos el reporte de allure
      run: mvn allure:report --file Calidad-Maven/pom.xml

    - name: Script para el servidor
      run: |
        echo '@echo off' > start_server.bat
        echo 'cd /d %~dp0' >> start_server.bat
        echo 'python -m http.server' >> start_server.bat
        echo 'echo.' >> start_server.bat
        echo 'echo Visit http://localhost:8000 to view the Allure report' >> start_server.bat
        echo 'echo.' >> start_server.bat
        echo 'pause' >> start_server.bat
      shell: bash

    - name: Instrucciones para los usuarios
      run: |
        echo 'Instrucciones para ver el reporte localmente:' > INSTRUCTIONS.txt
        echo '1. Asegurarse de que python esta isntalado y agregado a las variables de entorno.' >> INSTRUCTIONS.txt
        echo '2. Descomprimir allure-report-windows.zip file.' >> INSTRUCTIONS.txt
        echo '3. Iniciar el archivo start_server.bat haciendo dos veces click izquierdo.' >> INSTRUCTIONS.txt
        echo '4. Abrir el navegador y pegar la siguiente ruta http://localhost:8000.' >> INSTRUCTIONS.txt
        echo '5. Para detener el servidor, cerramos el promt del comando de windows.' >> INSTRUCTIONS.txt
      shell: bash

    - name: Reporte de allure en zip con el script y las instrucciones
      run: |
        zip -r allure-report-windows.zip Calidad-Maven/target/site/allure-maven-plugin start_server.bat INSTRUCTIONS.txt
      shell: bash

    - name: Reporte de allure comprimido con el script y las instrucciones
      uses: actions/upload-artifact@v3
      with:
        name: allure-report-windows
        path: allure-report-windows.zip


    
    
    









